import axios from "axios"
import { useEffect } from "react";

interface ICheck {
    func: (data: IUser) => void
}

// Generated by https://quicktype.io

export interface IData {
    status:  string;
    message: string;
    data:    IUser;
}

export interface IUser {
    id:                number;
    name:              string;
    email:             string;
    email_verified_at: null;
    created_at:        Date;
    updated_at:        Date;
    group_chats:       GroupChat[];
}

export interface GroupChat {
    id:         number;
    user_id:    number;
    slug:       string;
    text:       null;
    created_at: Date;
    updated_at: Date;
}



const Check = ({ func }: ICheck) => {
    useEffect(() => {
        const token = localStorage.getItem("token")
        if (token) {
            axios.post<IData>("http://127.0.0.1:8000/api/check", {}, {
                headers: {
                    Authorization: `Bearer ${token}`,
                    Accept: 'Application/json'
                }
            })
                .then(data => {
                    const fetched = data.data
                    func(fetched.data)
                })
        }
    }, [])
    return (
        <></>
    )
}

export default Check