import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Jakarta = localFont ({
  src: "./fonts/PlusJakartaSans-VariableFont_wght.ttf", variable : "--font-jakarta"
});


const CalSans = localFont ({
  src: "./fonts/CalSans-Regular.ttf", variable : "--font-CalSans"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <body className={Jakarta.variable + " " + CalSans.variable}>{children}</body> 
    </html>
  );
}
