import React from 'react'
import { IChartArea } from '../components/chatarea';

// Generated by https://quicktype.io

export interface IGroupChat {
    status:  string;
    message: string;
    data:    GroupChatData;
}

export interface GroupChatData {
    id:         number;
    user_id:    number;
    slug:       string;
    created_at: Date;
    text:string
    updated_at: Date;
    chats:      IChartArea[];
}

export interface Chat {
    id:            number;
    chat_group_id: number;
    chat:          string;
    query:         string;
    response:      string;
    created_at:    Date;
    updated_at:    Date;
    result:        Result[];
}

export interface Result {
    id:             number;
    student_id:     string;
    gender:         string;
    age:            number;
    study_hours:    number;
    attendance_pct: number;
    sleep_hours:    number;
    final_score:    number;
    passed:         number;
    created_at:     null;
    updated_at:     null;
}


const groupchat = () => {
  return (
    <div>groupchat</div>
  )
}

export default groupchat